### ISSUE TITLE
is generator support reference field type?

### ISSUE THREAD

**Issue by jiqimaogou** [mitulgolakiya/laravel-api-generator#102]
if I have a model reference another model, can generator support?

**Comment by gayanhewa** [comment]
Relationships ?

**Comment by jiqimaogou** [comment]
one to one, on two many, and many to many api generator?

**Comment by gayanhewa** [comment]
@mitulgolakiya I don't think we support this atm moment.

**Comment by mitulgolakiya** [comment]
Yes, it's in roadmap.

**Comment by mitulgolakiya** [comment]
Duplicate of https://github.com/mitulgolakiya/laravel-api-generator/issues/92
