### ISSUE TITLE
Feature: Support AdminLTE for scaffolding

### ISSUE THREAD

**Issue by viezel** [mitulgolakiya/laravel-api-generator#112]
More and more people are moving into AdminLTE for greater admin interfaces.
It would be great that this package could support the AdminLTE scaffolding.

**Comment by mitulgolakiya** [comment]
@viezel I am going to add field level and form level templates in some next releases. Then we can make another package which publishes templates of this generator which is compatible with AdminLTE. so we can make it fully modular without affecting a real generator package.

**Comment by viezel** [comment]
Sounds like a great plan

**Comment by phillipmadsen** [comment]
You should work on this first if you need the bladed files I  have them and can give them to you.

**Comment by Leelam** [comment]
Check this, https://github.com/Leelam/Laravel-with-basic-packages
