### ISSUE TITLE
Pagination on the list view

### ISSUE THREAD

**Issue by meena-kasi-optus** [mitulgolakiya/laravel-api-generator#113]
Hi ,

How can we get the pagination to work on the list page for CRUD generated with Laravel 5 CRUD generator.

Please could you provide me with the custom code to add to the controller to get the pagination working.

**Comment by mitulgolakiya** [comment]
It's already there, you just have to use option of pagination.

Here is the link: https://github.com/mitulgolakiya/laravel-api-generator#paginate-records

**Comment by meena-kasi-optus** [comment]
Thank you for the quick response Mitul.

I'm using the previous version for Laravel 5.0, check out 1.3 branch .

It does not seem to have the paginate option.

My project is a Laravel 5.0 Project and your help will be much appreciated.

How can I use pagination with my code ?

Below is my code snippet from the Controller:

/**
     \* Display a listing of the PackagePrice.
     *
     \* @param Request $request
     *
     \* @return Response
     */
    public function index(Request $request)
    {

```
    $input = $request->all();

    $result = $this->packagePriceRepository->search($input);

    $packagePrices = $result[0];

    $attributes = $result[1];

    return view('packagePrices.index')
        ->with('packagePrices', $packagePrices)
        ->with('attributes', $attributes);
}
```

Below is my code snippet from the Index List blade:

@extends('app')

@section('content')

```
<div class="container">

    @include('flash::message')

    <div class="row">
        <h1 class="pull-left">PackagePrices</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('packagePrices.create') !!}">Add New</a>
    </div>

    <div class="row">
        @if($packagePrices->isEmpty())
            <div class="well text-center">No PackagePrices found.</div>
        @else
            <table class="table">
                <thead>
                <th>Template Id</th>
        <th>Quantity</th>
        <th>Package Price</th>
                <th width="50px">Action</th>
                </thead>
                <tbody>

                @foreach($packagePrices as $packagePrice)
                    <tr>
                        <td>{!! $packagePrice->template_id !!}</td>
                <td>{!! $packagePrice->quantity !!}</td>
                <td>{!! $packagePrice->package_price !!}</td>
                        <td>
                            <a href="{!! route('packagePrices.edit', [$packagePrice->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                            <a href="{!! route('packagePrices.delete', [$packagePrice->id]) !!}" onclick="return confirm('Are you sure wants to delete this PackagePrice?')"><i class="glyphicon glyphicon-remove"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif
    </div>

</div>
```

@endsection

**Comment by mitulgolakiya** [comment]
First of all, you need to [publish](https://github.com/mitulgolakiya/laravel-api-generator/tree/1.3#customizing-generated-files) templates to make your own.

Then customize a repository search function to paginate records instead of get method.
Here is the doc for pagination: http://laravel.com/docs/5.1/pagination#paginating-eloquent-results

**Comment by meena-kasi-optus** [comment]
I've published my templates.

What would I need to update in my repository search function below ?

public function search($input)
    {
        $query = ExceptionEmployees::query();

```
    $columns = Schema::getColumnListing('exception_employees');
    $attributes = array();

    foreach($columns as $attribute){
        if(isset($input[$attribute]))
        {
            $query->where($attribute, $input[$attribute]);
            $attributes[$attribute] =  $input[$attribute];
        }else{
            $attributes[$attribute] =  null;
        }
    };

    return [$query->get(), $attributes];

}
```

**Comment by mitulgolakiya** [comment]
I think you should try to return `$query->paginate($pageSize)` instead of `$query->get()`. Where $pageSize is your page size.

And also you need to change `index.blade.php` to render pagination like: http://laravel.com/docs/5.1/pagination#displaying-results-in-a-view

**Comment by meena-kasi-optus** [comment]
Thank you very much for your help Mitul. 

The pagination works fine.

Much appreciate your help.
