### ISSUE TITLE
You need to update your fields.blade.stub

### ISSUE THREAD

**Issue by phillipmadsen** [mitulgolakiya/laravel-api-generator#117]
small typos to fix:  
## FILE: fields.blade.stub

**change**  **to** , 
**or even better yet** {{-- Submit Field --}}
## FILE: field.blade.stub

**change**  **to** , 
**or even better yet** {{-- $FIELD_NAME_TITLE$ Field--}}

**Its not to important but it throws errors in ide's.**

**Comment by mitulgolakiya** [comment]
Done
