### ISSUE TITLE
5.2 support please

### ISSUE THREAD

**Issue by vesper8** [mitulgolakiya/laravel-api-generator#128]
Unable to upgrade to Laravel 5.2 because of this package... hopefully nothing to serious =\ anyone know how to hack it?

**Comment by nickfan** [comment]
+1

**Comment by devSarry** [comment]
Ya even when creating a laravel project from 5.1.\* I'm getting 

```
Fatal error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\apiproperty\bootstrap\app.php on lin
e 14
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
```

after trying to do a composer update.

**Comment by iquantumtech** [comment]
The master branch was updated to support Laravel 5.2.  I created a new project to test and got the following error.  Anyone else experiencing the same result?

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package mitulgolakiya/laravel-api-generator could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Using:
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laracasts/flash": "dev-master",
        "laravelcollective/html": "5.2.*",
        "bosnadev/repositories": "dev-master",
        "mitulgolakiya/laravel-api-generator": "master"
    },

**Comment by rodelapena** [comment]
tha manual has an error (typo maybe) on installation process

this is my composer.json:
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/mitulgolakiya/laracast-flash"
        }
    ],
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2._",
        "laracasts/flash": "dev-master",
        "laravelcollective/html": "5.1._@dev",
        "bosnadev/repositories": "dev-master",
        "mitulgolakiya/laravel-api-generator": "dev-master"
    },

when i run composer 

odrigo@jarvis:~/Projects/mitul521 > composer update

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)  
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - laravelcollective/html 5.1.x-dev requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.0 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.1 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.2 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.3 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.4 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.5 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.6 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.7 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.8 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - laravelcollective/html v5.1.9 requires illuminate/session 5.1.\* -> satisfiable by illuminate/session[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - don't install illuminate/session v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.13|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.16|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.2|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.20|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.22|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.25|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.28|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.6|don't install laravel/framework v5.2.0
    - don't install illuminate/session v5.1.8|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.\* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6].
    - Installation request for laravelcollective/html 5.1.*@dev -> satisfiable by laravelcollective/html[5.1.x-dev, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].

just change

```
    "laravelcollective/html": "5.1.*@dev",
```

to 

```
    "laravelcollective/html": "5.2.*@dev",
```

and run composer update

**Comment by mitulgolakiya** [comment]
@rodelapena yes, I forgot to change it. Laravel 5.2 needs `laravelcollective/html` 5.2. I've updated doc. Also I have changed `laracasts/flash` to 1.3.

Just check it and let me know if problem still persist.
