### ISSUE TITLE
How to remove Request

### ISSUE THREAD

**Issue by azizgithub** [mitulgolakiya/laravel-api-generator#13]
Can I delete a Request file and straight to own validation in scaffold generator ?
Because in my opinion for a simple CRUD process i am not to use Request in order to code more simple. And may i to clone your repo and publish it with my style ?
Thanks.. :)

**Comment by mitulgolakiya** [comment]
@azizgithub,

You can delete the request file from your Request folder of Http and can modify controller in your way and can just use simple Request class injection instead of FormRequest. And you can always clone the repo and modify it in your way.

Just let me know if you face any problem. :)
