### ISSUE TITLE
Composer error with Laravel 5.1

### ISSUE THREAD

**Issue by sairam2188** [mitulgolakiya/laravel-api-generator#137]
Hi, 

Unable to run composer update. Get the following error:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: don't install laravel/framework v5.1.28
    - Conclusion: remove laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.26
    - Conclusion: don't install laravel/framework v5.1.25
    - Conclusion: don't install laravel/framework v5.1.24
    - Conclusion: don't install laravel/framework v5.1.23
    - Conclusion: don't install laravel/framework v5.1.22
    - Conclusion: don't install laravel/framework v5.1.21
    - Conclusion: don't install laravel/framework v5.1.20
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - mitulgolakiya/laravel-api-generator dev-master requires illuminate/support 5.2.\* -> satisfiable by illuminate/support[v5.2.0, v5.2.6, v5.2.7].
    - mitulgolakiya/laravel-api-generator dev-master requires illuminate/support 5.2.\* -> satisfiable by illuminate/support[v5.2.0, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.\* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].
    - Installation request for mitulgolakiya/laravel-api-generator dev-master -> satisfiable by mitulgolakiya/laravel-api-generator[dev-master].

My composer.json:

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
          "type": "git",
          "url": "https://github.com/mitulgolakiya/laracast-flash"
        }
    ],
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._",
        "doctrine/dbal": "v2.5.2",
        "mews/captcha": "^2.1",
        "barryvdh/laravel-dompdf": "^0.6.0",
        "maatwebsite/excel": "~2.0.0",
        "barryvdh/laravel-elfinder": "^0.3.4",
        "laracasts/flash": "dev-master",
        "laravelcollective/html": "5.1._@dev",
        "bosnadev/repositories": "dev-master",
        "mitulgolakiya/laravel-api-generator": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

Anyone know how to solve it?

**Comment by mitulgolakiya** [comment]
@sairam2188 which laravel and generator version you are using ?

**Comment by sairam2188** [comment]
@mitulgolakiya Laravel 5.1.27 and generator 1.4

**Comment by mitulgolakiya** [comment]
@sairam2188 I have just fixed readme. May be you were checking our `dev-master` of of generator.

Please go through the fresh installation and try again.

Don't forget to update versions as per new instruction.

```
"laracasts/flash": "dev-master",
"laravelcollective/html": "~5.1",
"bosnadev/repositories": "dev-master",
"mitulgolakiya/laravel-api-generator": "~1.4"
```

**Comment by sairam2188** [comment]
@mitulgolakiya I update my composer.json with your suggestion, but I get this message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mitulgolakiya/laravel-api-generator ~1.4 could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems

You know how to solve it?

**Comment by mitulgolakiya** [comment]
try it with

`"mitulgolakiya/laravel-api-generator": "1.4.x-dev"`

**Comment by sairam2188** [comment]
@mitulgolakiya it worked fine. Thank you.
