### ISSUE TITLE
Some feature request 

### ISSUE THREAD

**Issue by Pandahisham** [mitulgolakiya/laravel-api-generator#14]
I love laravel but absolutely hate boilerplate coding , since i am a newbe and don't lnow much about artisan command , i was thinking about building a frontend like Gii for Yii with angular so that the boiler plate code can be autogenerated and then copied to respective folder , but you have saved a lot of my time , thanks ,

some feature that would be awesome 
1.relationship , like: Post: hasMany Comment
2.seed file with faker types : body: fakertype : realtext
3.define input type in the view : body :textarea
4. some boilerplate for file / image uploading

**Comment by mitulgolakiya** [comment]
@Pandahisham,

Relationships and defining input types for view is already in next roadmap. And I will also take other things in next roadmap.

Thanks.
