### ISSUE TITLE
Singular routes

### ISSUE THREAD

**Issue by Mutahhar** [mitulgolakiya/laravel-api-generator#145]
```
php artisan infyom:scaffold $MODEL_NAME
```

is generating plural routes. For example if i want to scaffold projects.

The command `php artisan infyom:scaffold Project` it will generate `Route::resource( 'projects', 'ProjectController' );` route but I want the routes to be singular like `Route::resource( 'project', 'ProjectController' );` like default laravel works.

There should be an option to make route singular or plural in config file or CLI

**Comment by phillipmadsen** [comment]
I prefer the plural version myself but maybe it should be what is used in the generate command. 

> php artisan infyom:scaffold Project =  Route::resource( 'project', 'ProjectController' );
> 
> php artisan infyom:scaffold Projects =  Route::resource( 'projects', 'ProjectsController' );

I think by doing this it will be easier to keep track of and debug as well.

**Comment by Mutahhar** [comment]
@phillipmadsen your proposed suggestion is actually better.
