### ISSUE TITLE
Not able to create scaffold from table when there is a foreign key set

### ISSUE THREAD

**Issue by abin-andrews** [mitulgolakiya/laravel-api-generator#148]
Not able to create scaffold from table when a foreign key is set, if the table that is mentioned in --tableName and the --fromTable params are set the command crashes saying this in the console

[ErrorException]
Undefined offset: 1

**Comment by mitulgolakiya** [comment]
@netdotter787 this package is no longer maintained.
Switch to the updated one: https://github.com/InfyOmLabs/laravel-generator
