### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by lahaxearnaud** [mitulgolakiya/laravel-api-generator#2]
Hello,

This package is great ! It saves me some time today. :+1: 

Can you add some versions tag in order to have more stability. 

Perhaps you can tag the last commit with v0.1.

Sincerly,

Arnaud

**Comment by mitulgolakiya** [comment]
Thanks @lahaxearnaud,

That would be better if we run it in development stage for sometime. so we can get any fixes done if anything is found by any user. Then sure we will move with tags.

It's already in my queue to out the first version. will do it after sometime.

**Comment by mitulgolakiya** [comment]
First release is out.
