### ISSUE TITLE
Transform output data

### ISSUE THREAD

**Issue by almaweb** [mitulgolakiya/laravel-api-generator#23]
Hello,

Is it possible to add an option to transform output api data......an transformer.......

Thanks for this cool package

**Comment by mitulgolakiya** [comment]
@almaweb,

If I am not wrong then you are trying to get response in diff format then flag, data and message. Right ?

If it's so then, you can make you own ResponseManager. And after generating API controller, you can replace it in controller and send result in your own format.

**Comment by almaweb** [comment]
hello..
only data output......for no't showing structure of my db....
forexample created_at will be transformed in since...somethings like fractale

**Comment by mitulgolakiya** [comment]
Currently, it's not available in current version, as it's not a general requirement. so you have to do it by your self in your API controllers.

Or as I said, you can override ResponseManager by your own transformation class, which will transform the result before response is sent to user.

**Comment by almaweb** [comment]
I did and it'ok....
Thanks
