### ISSUE TITLE
[Proposal] Generate Scaffold and Api

### ISSUE THREAD

**Issue by lahaxearnaud** [mitulgolakiya/laravel-api-generator#3]
Hello,

Is it possible to add an option to generate web scaffold and api controller when we select to create a repository ?

Arnaud

**Comment by mitulgolakiya** [comment]
While creating API, we have to return a JSON or data, but while creating scaffold we have return views with that data. so I am not sure why you want to create scaffold as well as API Controller.

Can you describe the use case in bit more in detail like what exactly you want to do ?

**Comment by lahaxearnaud** [comment]
In my case i'm working an a domotic application based on laravel 5. I need to expose a web application (scaffold) but I also need to create an REST API for the mobile application.

**Comment by mitulgolakiya** [comment]
@lahaxearnaud,
It's done in new release v1.1.0. 
https://github.com/mitulgolakiya/laravel-api-generator/releases/tag/v1.1.0

**Comment by lahaxearnaud** [comment]
nice thanks
