### ISSUE TITLE
 generate CRUD without create table 

### ISSUE THREAD

**Issue by shanka12** [mitulgolakiya/laravel-api-generator#30]
Hi
I already got tables in database. I don't won't to create tables from command line. and I have migration tables class inside database folder.
How to generate CRUD through command line ?

Thank you.

**Comment by mitulgolakiya** [comment]
@shanka12,
Currently, it's not available to generate CRUD from database table or without migration. It's already in roadmap.
What you can do as of now is, just go through the whole process and do not migrate database at end of the CRUD generation. And just delete the newly created migration file if you already have migration.

**Comment by shanka12** [comment]
Thanks for your reply.
Ok. How do I add foreign key using command line?

**Comment by mitulgolakiya** [comment]
that's also in roadmap #24 to make it like laravel generators extended.
as of now, you can directly put if after generating migration file.

**Comment by shanka12** [comment]
Ok. Thank you for your help

**Comment by mitulgolakiya** [comment]
@shanka12, Just pushed very basic support for generating CRUD from existing table. Check it [here](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#generator-from-existing-tables)
Still some of the things are in process.
