### ISSUE TITLE
Keep asking for fields

### ISSUE THREAD

**Issue by tienkhoi** [mitulgolakiya/laravel-api-generator#31]
Hi,

Not sure if someone experience this issue.

I ran "php artisan mitul.generator:api Employee". The console asks for first field, I enter "name:string,255" and "required" for validation. The console asks for field again. At this point I want to finish my model so I left it blank and hit enter. But the console log doesn't let me enter. It keeps warning: "A value is required"
![image](https://cloud.githubusercontent.com/assets/7607653/7595261/ef95f042-f8b3-11e4-82b2-4edccede5b02.png)

**Comment by mitulgolakiya** [comment]
@tienkhoi,
Are you still facing this issue? Can you describe some more details, like which version you are using of Laravel and Generator ? Also your local environment ?

**Comment by gayanhewa** [comment]
This was fixed with the pull request I sent. Apparently this occurs  after an update to Laravel 5.1-dev branch. Probably caused by Symphony's console component's update.

**Comment by mitulgolakiya** [comment]
It's fixed in new version and now rather then left it as a blank, we have to write exit to finish.

**Comment by tienkhoi** [comment]
![image](https://cloud.githubusercontent.com/assets/7607653/8207232/e9a4db2c-14cd-11e5-9af7-0553abad5177.png)

Hi mitulgolakiya,

It still asks for a field. I typed exit but it didn't work. I'm using Laravel 5.1 with   "mitulgolakiya/laravel-api-generator": "1.3.*"

**Comment by mitulgolakiya** [comment]
For laravel 5.1, you should use [master](https://github.com/mitulgolakiya/laravel-api-generator/tree/master) branch. This issue is fixed in master branch.
