### ISSUE TITLE
Publish Error

### ISSUE THREAD

**Issue by KhaingWah** [mitulgolakiya/laravel-api-generator#33]
Hi, Mitul
I like this post and I would like to use this generator to get the better performance and to save my coding time.
I really appericiate for your post and sharing.
But when I publish the generator I got the following error, may be I would like to know the result.
I put the provider in app.php file.

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Laracasts\Flash\FlashServiceProvider' not found","file":"C:\Users\pc14\Desktop\xampp\htdocs\test\vendor\
\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php","line":158}}

Thanks In Advances,
Khaing.

**Comment by mitulgolakiya** [comment]
Please check if laracasts/flash is installed properly ?

**Comment by KhaingWah** [comment]
Hi mitul,
I didn't install for laracast and flash in my system bcos my laravel version is 4.1.*.
That's why. How can I resolve my problem that I dont really want to change my version.

Best Regards,
Khaing

**Comment by mitulgolakiya** [comment]
@KhaingWah,
This package will only work for Laravel 5 version. It doesn't have support for Laravel 4.
