### ISSUE TITLE
Custom templates?

### ISSUE THREAD

**Issue by rogue780** [mitulgolakiya/laravel-api-generator#38]
I'd like to be able to use my own templates or at least modify the included templates. Currently, since they reside in the vendor directory, it isn't feasible to edit those.

Is there a way to specify custom templates to be used?

**Comment by mitulgolakiya** [comment]
@rogue780,
sure. I will at it to the roadmap.

**Comment by mitulgolakiya** [comment]
Released in 1.3.2.
