### ISSUE TITLE
Consider Dingo API features

### ISSUE THREAD

**Issue by viezel** [mitulgolakiya/laravel-api-generator#40]
The Dingo API package has a lot of features that this generator does not implement. Important features like versioning, rate limits, auth like oauth, internal requests and super flexible to override. 
https://github.com/dingo/api/wiki

Would you consider implementing this package?

**Comment by mitulgolakiya** [comment]
Yes, we can add these features in roadmap.

**Comment by KIVagant** [comment]
@viezel, if you already use dingo/api in your project and if you have modificated example of API controller with all CRUD methods – send me an example, please.

**Comment by viezel** [comment]
sorry, I dont have a combo of the generator and Dingo.. I used dingo in previous projects, and its super flexible and consistent in all of its features.. I would make this generator very good to implement it.

**Comment by KIVagant** [comment]
Just note: Dingo/api does not have a stable release for Laravel 5 and/or Lumen.

**Comment by viezel** [comment]
This is a great issue to follow to gain more knowledge about L5 and Dingo:
https://github.com/dingo/api/issues/398

**Comment by KIVagant** [comment]
Dingo/api does not contain the actual documentation. Yesterday I tried to install it, but got a lot of problems. And I [asked somebody](https://github.com/dingo/api/issues/412) about clear examples of usage in L5, they does not have it yet. 
If you have an example with clear CRUD API in L5 – show it, please. I can help integrate it to api-generator, but only if it really work.

**Comment by KIVagant** [comment]
@viezel, I have successfully included dingo library in my test project, so in closest future I will make a PR for integrate it to this generator.

**Comment by viezel** [comment]
sounds great.. looking forward for this. thanks !

**Comment by KIVagant** [comment]
Waiting for [related issue](https://github.com/dingo/api/issues/419)

**Comment by KIVagant** [comment]
Hello, @mitulgolakiya and @viezel 

DO NOT MERGE THIS. [Related pull](https://github.com/dingo/api/pull/420) should be merged first.

Here is critical changes for Api Generator. Now it can generate a powerfull RESTlike api.

You can try it first.
1. Go to [example branch](https://github.com/KIVagant/learning-laravel-5/tree/api-generator)
2. Clone it, run migrations and follow to the pages:

#### /api

![Awesome](http://i.imgur.com/bR3E58A.png)

#### /api/errors

![Brilliant](http://i.imgur.com/MlymUEu.png)

#### /api/dingos

![OMG](http://i.imgur.com/zBGV22o.png)

Follow the [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS) links! Keep calm and use REST!

## Changelist
- First, the [routes.php](https://github.com/KIVagant/learning-laravel-5/blob/api-generator/app/Http/routes.php#L33) now used a dingo/api provider. Generator make it by default for new models.
- Second, responses now can be returned with `$this->response()->array($response);`. Here you free to use any [dingo responses](https://github.com/dingo/api/wiki/Responses), but I'm already make some special inside generator.
- APIController have a new property $hateoas. Call this wrapper and replace any placeholders in url's:

```
$response = $this->structurizeResponse($articles->toArray(), self::MSG_UPDATED, true, ['%id' => $id]);
```
- New [class Errors](https://github.com/KIVagant/laravel-api-generator/blob/master/src/Mitul/Generator/Errors.php) added. Extend it in project and add more special errors in list. In future, we can move this to separate config file.
- You can throw any Exceptions inside API with new helper methods:
  - `Errors::throwHttpExceptionWithCode()` – for registered errors
  - `Errors::throwHttpException()` – for not registered errors
  -  or just like this for any errors (but you lost some nice wrappers functionality):

```
$exception = new Exception(404, 'Childs crying');
$exception->replacements = [ // Yeah, yeah, it's not brilliant OOP, but believe me, just a simplest way
     ':payload' => $some_data,
     ':my_field' => $new_field // You can use here any fields from api.php > errorFormat
];
throw $exception;
```

**Comment by KIVagant** [comment]
Here is example of routes for two models (mixed manually):

```
$api = app('api.router');
$api->group([
    'version' => 'v1',
//    'prefix' => 'api', // API_DOMAIN setted in .env, so we don't need a prefix
    'namespace' => 'App\Http\Controllers\API',
], function ($api) {
    $api->resource('dingos', 'DingoAPIController');
    $api->resource('news', 'NewsAPIController');
    $api->get('errors/{id}', function($id) {
        return \Mitul\Generator\Errors::getErrors([$id]);
    });
    $api->get('errors', function() {
        return \Mitul\Generator\Errors::getErrors([], [], true);
    });
    $api->get('/', function() {
        $links = [
            'news' => \App\Http\Controllers\API\NewsApiController::getHATEOAS(),
            'dingos' => \App\Http\Controllers\API\DingoApiController::getHATEOAS()
        ];

        return ['links' => $links];
    });
});
```

**Comment by viezel** [comment]
yeah .. thats a nice example.
I love the internal requests provided by Dingo.

**Comment by KIVagant** [comment]
We reached [a compromise](https://github.com/dingo/api/pull/420#issuecomment-106269728) with the author dingo, so [this pull](https://github.com/mitulgolakiya/laravel-api-generator/issues/54) can be merged. 
Please, [download and test it](https://github.com/KIVagant/learning-laravel-5/tree/api-generator) and ask your questions.
