### ISSUE TITLE
What about 404 HTTP status?

### ISSUE THREAD

**Issue by KIVagant** [mitulgolakiya/laravel-api-generator#42]
Why API 'not found' has return http status code 200? Could you make a correct 404 http status?

> GET /api/articles/BADID HTTP/1.1
> ...
> < HTTP/1.1 200 OK
> < Content-Type: application/json
> {"flag":false,"message":"Article not found","code":1111}

P.S.: What does it mean '1111' code? Where I can find full list of this codes?

Thank you for excellent generator.

**Comment by mitulgolakiya** [comment]
@KIVagant,
you can find a full code list [here](https://github.com/mitulgolakiya/laravel-api-generator/blob/1.3/src/Mitul/Generator/Constants/Constants.php).

But I will make it to work like send 404 when record is not found.

**Comment by KIVagant** [comment]
This issue depends to [dingo/api](https://github.com/mitulgolakiya/laravel-api-generator/issues/40).
Maybe I will close it tomorrow.

**Comment by gayanhewa** [comment]
Its possible to fall back and use the Symphony standard HTTP response codes. It comes bundled with laravel.

```
Symfony\Component\HttpFoundation\Response::$statusTexts
```

**Comment by KIVagant** [comment]
Yes, I will change all templates for using dingo/api. So standart HTTP Responses will be there.
