### ISSUE TITLE
Contribution guidelines and issues in progress

### ISSUE THREAD

**Issue by gayanhewa** [mitulgolakiya/laravel-api-generator#51]
It would be great to know what tasks are currently in progress and what can be picked up to fix/build. That way someone could contribute without worrying if work on a particular task has already started ?

**Comment by mitulgolakiya** [comment]
I am already preparing one trello board where everyone can see what are the tasks in queue and can post a new requirement. Will share it soon.

**Comment by mitulgolakiya** [comment]
Here is the [Trello Board](https://trello.com/b/fCd70vkR/laravel-api-generator-development-board).

**Comment by gayanhewa** [comment]
:+1:
