### ISSUE TITLE
Admin interface for building

### ISSUE THREAD

**Issue by viezel** [mitulgolakiya/laravel-api-generator#55]
Could be very cool to create an admin interface for building the APIs. 
Have a look at apigility, and checkout their video
https://docs.google.com/file/d/0B3DjV-SlG3QbUnFNMTZ2RnhfSkk/view

It seems simple, powerful and we could do the same in Laravel.

**Comment by mitulgolakiya** [comment]
@viezel, it's already in ideas. Just check the full roadmap here #51 
[Here](https://trello.com/c/eQ1iDWIU/12-fully-featured-ui-interface-for-generator) is the card for interface builder.

**Comment by viezel** [comment]
@mitulgolakiya, does that also account for the auto documentation?

**Comment by mitulgolakiya** [comment]
Currently, it's just as an Idea, and I am adding features into that. so can add auto document support into it. And we can use something like [swagger](https://github.com/swagger-api/swagger-ui) or any API Doc tool.

**Comment by viezel** [comment]
sounds good.
