### ISSUE TITLE
how to override routes.php generated code

### ISSUE THREAD

**Issue by lorvent** [mitulgolakiya/laravel-api-generator#60]
I want to add prefix of admin to code generated to routes.php

how can i do that?

Thanks.

**Comment by mitulgolakiya** [comment]
It's not support in this release, but it's done and will be included in next release which will be out in around one week with the support of Laravel 5.1 and many more features.

**Comment by lorvent** [comment]
thanks for response mitul

**Comment by mitulgolakiya** [comment]
@lorvent,
check out master branch. now it's supported in new version. you can [publish templates](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#customize-templates) then you can change `/resources/api-generator-templates/routes/scaffold_routes.stub` and can add prefix into that.

**Comment by lorvent** [comment]
much thanks for the response mitul

great repo
