### ISSUE TITLE
No Support for pagination

### ISSUE THREAD

**Issue by codeyash** [mitulgolakiya/laravel-api-generator#61]
Its not hard to implement and most important features in listing items from DB.

Please add a support for this.

**Comment by mitulgolakiya** [comment]
it's already in [roadmap](https://trello.com/b/fCd70vkR/laravel-api-generator-development-board) and will be included in next release which will be out in around one week with support of Laravel 5.1 and many more features.

**Comment by mitulgolakiya** [comment]
@codeyash,
pagination support added. Check it [here](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#paginate-records)

**Comment by codeyash** [comment]
cool. Thanks buddy.
