### ISSUE TITLE
I can't finish the generator

### ISSUE THREAD

**Issue by betoflakes** [mitulgolakiya/laravel-api-generator#64]
I am creating a scaffold_api, but when I left blank to finish is still requiring a value, but I have finished to add values. It's a issue?

```
 Field::
 >

 [ERROR] A value is required.

 Field::
 >
```

I am working with last version: v1.3.3

**Comment by anheru88** [comment]
you need to write exit.

**Comment by mitulgolakiya** [comment]
@betoflakes,
May be it was a error because of new console component form symfony. But I am not sure. Now I updated generator and you need to write exit to finish the generator.

**Comment by erickosma** [comment]
I had to add to file   vendor/mitulgolakiya/laravel-api-generator/src/Mitul/Generator/CommandData.php  
in the function  getInputFields()  the  condition 

```
if(empty($fieldInputStr) || $fieldInputStr == "exit")
            break;
```

for this to work
