### ISSUE TITLE
trying to install dev-master but cannot resolve laracast-flash dev-master

### ISSUE THREAD

**Issue by longestdrive** [mitulgolakiya/laravel-api-generator#72]
Hi
I'm trying to install into a L5.1 app.

I've updated composer.json to include the repository and the package as described.

```
"mitulgolakiya/laravel-api-generator": "dev-master"
```

But when trying to do a composer update I get this error:

```
Problem 1
- Installation request for mitulgolakiya/laravel-api-generator dev-master -> satisfiable by mitulgolakiya/laravel-api-generator[dev-master].
- mitulgolakiya/laravel-api-generator dev-master requires laracasts/flash dev-master -> no matching package found.
```

Not clear what I should do now as unable to update the dependancy?

**Comment by mastergap** [comment]
I have the same problem. I'm trying to make the installation on Windows. I will try to install it on Linux later this night...

**Comment by longestdrive** [comment]
Yep mine is a windows install as well. I'll try through the vagrant box as well

**Comment by longestdrive** [comment]
ok tried it in a vagrant box and same issue.

**Comment by longestdrive** [comment]
I've added laracasts/flash as a dependency to my composer.json (as dev-master) which installs correctly but when I then try to install this package the error returns. In your composer.json does the repository need to be added to this packages composer.json?

**Comment by mitulgolakiya** [comment]
This issue is also reported by one another use as well. I am checking into this issue.

**Comment by mitulgolakiya** [comment]
There was some problem, composer is not installing `dev-master` packages where `minimum-stability` is `stable` (which is default).

I found an alternative, where you have to specify `dev-master` packages in your root directory `composer.json` and it worked.

I updated [doc](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#installation), check and let me know if problem still persist.

**Comment by longestdrive** [comment]
Yep - that resolved it - thank you
