### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phillipmadsen** [mitulgolakiya/laravel-api-generator#73]
This is not really an issue but i could not find a place to add requests or possible features. I am trying to have your plugin make a few more things and tweek the routing a little bit and was wondering if you were up for helping. 

Here is what im trying to do. 
This currently builds this:
The artisan command can generate the following items:
- Migration File
  - Model
  - Repository
  - Controller
  - View
    - index.blade.php
    - show.blade.php
    - create.blade.php
    - edit.blade.php
    - fields.blade.php
  - adjusts routes.php

But i am trying to make it do this:
- Migration File
- Model/Admin
- Model
- Repository
- Controller
- View (admin template)
  - <ModelName>
    - Admin/index.blade.php
    - Admin/show.blade.php
    - Admin/create.blade.php
    - Admin/edit.blade.php
    - Admin/fields.blade.php
- View (frontend pubic site template)
  - <ModelName>
    - Frontend/live.blade.php
- adjusts routes.php (for admin and live front end)

Do you have the time to help with this or can you give me some pointers that will make it easier. I am new to scaffold and will learn it if i have to. 

Thanks for the awesome package you already created. now hopefully we can make it better.

**Comment by mitulgolakiya** [comment]
@phillipmadsen,
you can modify paths in your published `generator.php` to generate views on some other paths. [Here](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#configuration) is the documentation for that.

But I am not sure about `Frontend/live.blade.php`. What exactly you want to put content into that file ?
