### ISSUE TITLE
Error in generated Controller

### ISSUE THREAD

**Issue by mastergap** [mitulgolakiya/laravel-api-generator#74]
Hi, I'm having the following error in a generated controller:

```
Cannot use Mitul\Controller\AppBaseController as Controller because the name is already in use
```

The line that leads to this error is:

``` php
use Mitul\Controller\AppBaseController as Controller;
```

**Comment by mitulgolakiya** [comment]
Can you post your generated controller code here ?

**Comment by tantam** [comment]
I run "php artisan mitul.generator:scaffold_api Project"

![screen shot 2015-07-03 at 3 49 00 pm](https://cloud.githubusercontent.com/assets/3469994/8495860/0cf5ec40-219b-11e5-962c-455d55602759.png)

**Comment by mitulgolakiya** [comment]
@tantam,
which version you are using ? Laravel version and Api Generator version ?

**Comment by maztch** [comment]
This is because currently exists a Controller class in your controllers folders.

You can solve it publishing templates: 

```
php artisan mitul.generator:publish --templates
```

and edit first lines from the file resources/api-generator-templates/controller/AppBaseController.php
to this:

```
<?php namespace $NAMESPACE_CONTROLLER$;

use $NAMESPACE_APP$\Http\Controllers\Controller as AppController;
use Illuminate\Http\Request;
use Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

class AppBaseController extends AppController
{
```

**Comment by mitulgolakiya** [comment]
This is fixed in master branch. Now we are using `AppBaseController` instead of `Controller`.
