### ISSUE TITLE
Error when i use another App name

### ISSUE THREAD

**Issue by wolvexcl** [mitulgolakiya/laravel-api-generator#76]
![image](https://cloud.githubusercontent.com/assets/13147564/8539367/e7e03e5c-2450-11e5-809d-65622adc186a.png)

**Comment by mitulgolakiya** [comment]
may be you are using diff layout. so you should publish your custom templates and you should adjust your layout and prefix by the way you are using.

[Here](https://github.com/mitulgolakiya/laravel-api-generator/tree/master#customize-templates) is the link to publish your templates.
