### ISSUE TITLE
integration with sleeping-owl/admin

### ISSUE THREAD

**Issue by augustocsoa** [mitulgolakiya/laravel-api-generator#78]
when I run the command:
php artisan mitul.generator:scaffold_api Post --fieldsFile="fields.json"
everything works!

but when i run:
php artisan route: list
I get this error:
root @ gateway: / var / www / htdocs / laranew # php artisan route: list

   [ReflectionException]
   Class App \ Http \ Controllers \ App \ Http \ Controllers \ API \ PostAPIController does not exist

What do I do wrong?
Is there a way to make an integration with sleeping-owl / admin and other ??
Tnks.

**Comment by mitulgolakiya** [comment]
Try to run composer dump-autoload after all your code generation. May be that can help.
