### ISSUE TITLE
error starting from scratch

### ISSUE THREAD

**Issue by rodelapena** [mitulgolakiya/laravel-api-generator#82]
hi Mitul,

i have a working project with your generator, suddenly between july 13 and today something got broken, i looked for an error on my code but didn't find anything.

finally i created a project from scratch following your steps and something is not working, some route.php error shows, in my working project have a similar issue, but with api routes

please help

rodrigo@jarvis:~/Projects > laravel new mitul
Crafting application...

> php artisan clear-compiled
> php artisan optimize
> Generating optimized class loader
> Compiling common classes
> php artisan key:generate
> Application key [p4PtFJu7G9tqCa89fbFK25MNTn5cM867] set successfully.
> Application ready! Build something amazing.

rodrigo@jarvis:~/Projects > cd mitul/

rodrigo@jarvis:~/Projects/mitul > composer update

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)         
> - Removing league/flysystem (1.0.9)
> - Installing league/flysystem (1.0.10)
>   Downloading: 100%  
- Removing laravel/framework (v5.1.7)
- Installing laravel/framework (v5.1.8)
  Downloading: 100%         
- Installing bosnadev/repositories (dev-master 637c703)
  Loading from cache
- Installing mitulgolakiya/laravel-api-generator (dev-master 6283290)
  Loading from cache
- Installing laracasts/flash (dev-master 719af83)
  Cloning 719af83a720707bfbd7cf5a08e80158378bf5ecf
- Installing laravelcollective/html (5.1.x-dev c93974c)
  Loading from cache

mitulgolakiya/laravel-api-generator suggests installing doctrine/dbal (Required to use generator from existing table.)
Writing lock file
Generating autoload files

> php artisan optimize
> Generating optimized class loader
> Compiling common classes

rodrigo@jarvis:~/Projects/mitul > php artisan vendor:publish --provider="Mitul\Generator\GeneratorServiceProvider"

Copied File [/vendor/mitulgolakiya/laravel-api-generator/config/generator.php] To [/config/generator.php]
Publishing complete for tag []!

rodrigo@jarvis:~/Projects/mitul > php artisan mitul.generator:publish
common views published
/home/rodrigo/Projects/mitul/resources/views/common
api_routes.php generated
/home/rodrigo/Projects/mitul/app/Http/api_routes.php

  [Illuminate\Contracts\Filesystem\FileNotFoundException]  
  /home/rodrigo/Projects/mitul/app/Http/routes.php         

  [League\Flysystem\FileNotFoundException]  
  File not found at path: home/rodrigo/Projects/mitul/app/Http/routes.php

**Comment by mitulgolakiya** [comment]
@rodelapena, may be, It is because of your mismatch storage root path in `config/filesystems.php`.

I reverted those changes as of now, and you should be able to now publish it. Check and let me know if problem persist.

**Comment by rodelapena** [comment]
OK everything is working again! thanks, what do i have to do to have the last commit working with my config?

thanks for your awesome generator!
