### ISSUE TITLE
php artisan route:list error

### ISSUE THREAD

**Issue by Trexology** [mitulgolakiya/laravel-api-generator#89]
when running "php artisan route:list"

I get the following error:

[ReflectionException]  
  Class App\Http\Controllers\API\AuthController does not exist

It only happen to the API route, scaffold routes are not affected. Apart from that, everything works well!

**Comment by zhekaus** [comment]
Did you create this controller using laravel-api-generator?

**Comment by Trexology** [comment]
Oh wait, I realize it was a bug on my end. Will close this issue now. Thanks
