### ISSUE TITLE
How To Create Custom Error Messages 

### ISSUE THREAD

**Issue by azizgithub** [mitulgolakiya/laravel-api-generator#9]
Hay, I want to set own custom error messages on validation, for example rules required i want to set error to Do Not Blank.. etc.
How i do this ?
Thanks ..

**Comment by mitulgolakiya** [comment]
@azizgithub,
While defining model validations on field, you can define custom messages like this,
http://laravel.com/docs/4.2/validation#custom-error-messages

We are using laravel validation only and not using any other validation stuff. so above link should work.
