### ISSUE TITLE
route:cache cause api routes miss

### ISSUE THREAD

**Issue by nickfan** [mitulgolakiya/laravel-api-generator#90]
route:cache cause api routes miss

config: generator.php

```
    'path_api_routes'          => app_path('Http/api_routes.php'),
```

routes.php:

```
Route::group(['prefix' => 'api', 'namespace' => 'API'], function ()
{
    Route::group(['prefix' => 'v1'], function ()
    {
        include_once Config::get('generator.path_api_routes');
    });
});
```

if i use php artisan route:cache
then run php artisan route:list
the include api routes not exists.

when i use php artisan route:clear
then run php artisan route:list
the include api routes show up again.

**Comment by mitulgolakiya** [comment]
it's done. just update to the latest code and you need to update your `routes.php` as

```
require Config::get('generator.path_api_routes');
```
