### ISSUE TITLE
app/Http/api_routes.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by jiqimaogou** [mitulgolakiya/laravel-api-generator#95]
app/Http/api_routes.php): failed to open stream: No such file or directory

**Comment by gayanhewa** [comment]
Looks like you are missing the api_routes file , double check the Service provider that loads the route files.

**Comment by mitulgolakiya** [comment]
@jiqimaogou Have you completed proper installation steps ? Most importantly this step. https://github.com/mitulgolakiya/laravel-api-generator#publish--initialization

**Comment by ghost** [comment]
Hi,
I have removed api_ from everywhere, its start working for me.

**Comment by francistito** [comment]
i complete proper installation step but still problem exist...
